import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { SUBJECT_HEADER, actorIds, gateGuardApi } from '@/lib/guardSession';
import { guardCorsHeaders } from '@/lib/guardCors';

/**
 * Guard app API gate (see src/lib/guardSession.ts). Checks the session token against the guard
 * the request acts for, and passes the verified guard id on to the route in SUBJECT_HEADER.
 */
async function guardApiGate(req: NextRequest, pathname: string): Promise<NextResponse> {
  let body: unknown = null;
  const type = req.headers.get('content-type') ?? '';
  if (req.method !== 'GET' && req.method !== 'HEAD' && type.includes('application/json')) {
    body = await req.clone().json().catch(() => null);
  }
  const result = await gateGuardApi(req, pathname, actorIds(req.nextUrl.searchParams, body));
  if (!result.ok) {
    return NextResponse.json({ success: false, code: result.code, message: result.message }, { status: result.status });
  }
  // Never trust a subject header the client sent itself.
  const headers = new Headers(req.headers);
  headers.delete(SUBJECT_HEADER);
  if (result.subject) headers.set(SUBJECT_HEADER, result.subject);
  return NextResponse.next({ request: { headers } });
}

export async function proxy(req: NextRequest) {
  const pathname = req.nextUrl.pathname;
  const hostname = req.headers.get('host') || '';

  if (pathname.startsWith('/api/guard/')) {
    const cors = guardCorsHeaders(req.headers.get('origin'));
    const response = req.method === 'OPTIONS'
      ? new NextResponse(null, { status: cors ? 204 : 403 })
      : await guardApiGate(req, pathname);
    response.headers.append('Vary', 'Origin');
    for (const [key, value] of Object.entries(cors ?? {})) response.headers.set(key, value);
    return response;
  }

  // API calls and static assets MUST pass through directly without subdomain rewrites/redirects
  if (
    pathname.startsWith('/api/') ||
    pathname.startsWith('/_next/') ||
    pathname.includes('.')
  ) {
    return NextResponse.next();
  }

  const isOpsSubdomain = hostname.startsWith('ops.') || hostname.startsWith('ops-');
  const isTrinetraSubdomain = hostname.startsWith('trinetra.') || hostname.startsWith('trinetra-');
  const isApSubdomain = hostname.startsWith('ap.') || hostname.startsWith('ap-');
  const isGuardSubdomain = hostname.startsWith('guards.') || hostname.startsWith('guards-');

  let res: NextResponse;

  if (isApSubdomain) {
    // Repair links generated by the older `/ap` prefix matcher, which turned
    // `/apply/<token>` into `/ply/<token>`.
    if (pathname.startsWith('/ply/')) {
      const publicUrl = req.nextUrl.clone();
      publicUrl.pathname = `/apply/${pathname.slice('/ply/'.length)}`;
      return NextResponse.rewrite(publicUrl);
    }

    // Public candidate forms must never be routed through the authenticated
    // Agency Portal. Rewrite old AP-host links so they still work without a
    // redirect loop; newly generated links use the public careers host.
    if (pathname === '/apply' || pathname.startsWith('/apply/')) {
      const publicForm = req.nextUrl.clone();
      publicForm.pathname = pathname;
      return NextResponse.rewrite(publicForm);
    }

    // Clean URL guard for agencyportal subdomain
    // `/apply/...` is a public recruitment form, not an Agency Portal path.
    // Do not treat its first two characters (`/ap`) as the old `/ap` prefix.
    if (pathname.startsWith('/agencyportal') || pathname === '/ap' || pathname.startsWith('/ap/')) {
      const cleanPath = pathname.replace(new RegExp('^/(agencyportal|ap)'), '') || '/';
      const redirectUrl = req.nextUrl.clone();
      redirectUrl.pathname = cleanPath;
      return NextResponse.redirect(redirectUrl, 308);
    }

    const isStaticOrApi =
      pathname.startsWith('/api') ||
      pathname.startsWith('/_next') ||
      pathname.includes('.');

    const isApLoginPage = pathname === '/login' || pathname === '/agencyportal/login';

    if (!isApLoginPage && !isStaticOrApi) {
      const token = req.cookies.get('suraksha_ap_token')?.value || req.cookies.get('suraksha_token')?.value;
      const loginTimeStr = req.cookies.get('suraksha_login_time')?.value;

      let isExpired = false;
      if (loginTimeStr) {
        const loginTime = parseInt(loginTimeStr, 10);
        const SEVEN_DAYS_MS = 7 * 24 * 60 * 60 * 1000;
        if (!isNaN(loginTime) && Date.now() - loginTime > SEVEN_DAYS_MS) {
          isExpired = true;
        }
      }

      if (!token || isExpired) {
        const loginUrl = new URL('/login', req.url);
        if (isExpired) loginUrl.searchParams.set('expired', '1');
        const response = NextResponse.redirect(loginUrl);
        if (isExpired) {
          response.cookies.delete('suraksha_ap_token');
          response.cookies.delete('suraksha_token');
          response.cookies.delete('suraksha_user');
          response.cookies.delete('suraksha_login_time');
        }
        return response;
      }
    }

    if (isApLoginPage) {
      const token = req.cookies.get('suraksha_ap_token')?.value || req.cookies.get('suraksha_token')?.value;
      const loginTimeStr = req.cookies.get('suraksha_login_time')?.value;
      let isExpired = false;
      if (loginTimeStr) {
        const loginTime = parseInt(loginTimeStr, 10);
        const SEVEN_DAYS_MS = 7 * 24 * 60 * 60 * 1000;
        if (!isNaN(loginTime) && Date.now() - loginTime > SEVEN_DAYS_MS) isExpired = true;
      }
      if (token && !isExpired) {
        return NextResponse.redirect(new URL('/', req.url));
      }
    }

    if (!isStaticOrApi) {
      const rewriteUrl = req.nextUrl.clone();
      rewriteUrl.pathname = `/agencyportal${pathname === '/' ? '' : pathname}`;
      res = NextResponse.rewrite(rewriteUrl);
    } else {
      res = NextResponse.next();
    }
  } else if (isTrinetraSubdomain) {
    // CLEAN URL GUARD for trinetra subdomain:
    // If browser requests trinetra.localhost/trinetra or trinetra.localhost/trinetra/features,
    // redirect cleanly to trinetra.localhost/ or trinetra.localhost/features!
    if (pathname.startsWith('/trinetra')) {
      const cleanPath = pathname.replace(new RegExp('^/trinetra'), '') || '/';
      const redirectUrl = req.nextUrl.clone();
      redirectUrl.pathname = cleanPath;
      return NextResponse.redirect(redirectUrl, 308);
    }

    const isStaticOrApi =
      pathname.startsWith('/api') ||
      pathname.startsWith('/_next') ||
      pathname.includes('.');

    if (!isStaticOrApi) {
      const rewriteUrl = req.nextUrl.clone();
      rewriteUrl.pathname = `/trinetra${pathname === '/' ? '' : pathname}`;
      res = NextResponse.rewrite(rewriteUrl);
    } else {
      res = NextResponse.next();
    }
  } else if (isOpsSubdomain) {
    if (pathname.startsWith('/ops/') || pathname === '/ops' || pathname.startsWith('/admin/')) {
      const cleanPath = pathname.replace(new RegExp('^/(ops|admin)'), '') || '/';
      const redirectUrl = req.nextUrl.clone();
      redirectUrl.pathname = cleanPath;
      return NextResponse.redirect(redirectUrl, 308);
    }

    const isStaticOrApi =
      pathname.startsWith('/api') ||
      pathname.startsWith('/_next') ||
      pathname.includes('.');

    const isOpsLoginPage = pathname === '/login';

    if (!isOpsLoginPage && !isStaticOrApi) {
      const token = req.cookies.get('suraksha_token')?.value;
      const loginTimeStr = req.cookies.get('suraksha_login_time')?.value;

      let isExpired = false;
      if (loginTimeStr) {
        const loginTime = parseInt(loginTimeStr, 10);
        const SEVEN_DAYS_MS = 7 * 24 * 60 * 60 * 1000;
        if (!isNaN(loginTime) && Date.now() - loginTime > SEVEN_DAYS_MS) {
          isExpired = true;
        }
      }

      if (!token || isExpired) {
        const loginUrl = new URL('/login', req.url);
        if (isExpired) loginUrl.searchParams.set('expired', '1');
        const response = NextResponse.redirect(loginUrl);
        if (isExpired) {
          response.cookies.delete('suraksha_token');
          response.cookies.delete('suraksha_user');
          response.cookies.delete('suraksha_login_time');
        }
        return response;
      }
    }

    if (isOpsLoginPage) {
      const token = req.cookies.get('suraksha_token')?.value;
      const loginTimeStr = req.cookies.get('suraksha_login_time')?.value;
      let isExpired = false;
      if (loginTimeStr) {
        const loginTime = parseInt(loginTimeStr, 10);
        const SEVEN_DAYS_MS = 7 * 24 * 60 * 60 * 1000;
        if (!isNaN(loginTime) && Date.now() - loginTime > SEVEN_DAYS_MS) isExpired = true;
      }
      if (token && !isExpired) {
        return NextResponse.redirect(new URL('/', req.url));
      }
    }

    if (!isStaticOrApi) {
      const rewriteUrl = req.nextUrl.clone();
      rewriteUrl.pathname = `/ops${pathname === '/' ? '' : pathname}`;
      res = NextResponse.rewrite(rewriteUrl);
    } else {
      res = NextResponse.next();
    }
  } else if (isGuardSubdomain) {
    if (pathname.startsWith('/guardportal') || pathname === '/guardportal') {
      const cleanPath = pathname.replace(new RegExp('^/(guardportal)'), '') || '/';
      const redirectUrl = req.nextUrl.clone();
      redirectUrl.pathname = cleanPath;
      return NextResponse.redirect(redirectUrl, 308);
    }

    const isStaticOrApi =
      pathname.startsWith('/api') ||
      pathname.startsWith('/_next') ||
      pathname.includes('.');

    if (!isStaticOrApi) {
      const rewriteUrl = req.nextUrl.clone();
      rewriteUrl.pathname = `/guardportal${pathname === '/' ? '' : pathname}`;
      res = NextResponse.rewrite(rewriteUrl);
    } else {
      res = NextResponse.next();
    }
  } else {
    const isProtectedApPath = pathname.startsWith('/agencyportal') && pathname !== '/agencyportal/login';
    if (isProtectedApPath) {
      const token = req.cookies.get('suraksha_ap_token')?.value || req.cookies.get('suraksha_token')?.value;
      if (!token) {
        return NextResponse.redirect(new URL('/agencyportal/login', req.url));
      }
    }

    const isProtectedAdminPath =
      pathname.startsWith('/admin') && pathname !== '/admin/login';

    if (isProtectedAdminPath) {
      const token = req.cookies.get('suraksha_token')?.value;
      const loginTimeStr = req.cookies.get('suraksha_login_time')?.value;
      let isExpired = false;
      if (loginTimeStr) {
        const loginTime = parseInt(loginTimeStr, 10);
        const SEVEN_DAYS_MS = 7 * 24 * 60 * 60 * 1000;
        if (!isNaN(loginTime) && Date.now() - loginTime > SEVEN_DAYS_MS) isExpired = true;
      }
      if (!token || isExpired) {
        const loginUrl = new URL('/admin/login', req.url);
        if (isExpired) loginUrl.searchParams.set('expired', '1');
        const response = NextResponse.redirect(loginUrl);
        if (isExpired) {
          response.cookies.delete('suraksha_token');
          response.cookies.delete('suraksha_user');
          response.cookies.delete('suraksha_login_time');
        }
        return response;
      }
    }

    if (pathname === '/admin/login') {
      const token = req.cookies.get('suraksha_token')?.value;
      const loginTimeStr = req.cookies.get('suraksha_login_time')?.value;
      let isExpired = false;
      if (loginTimeStr) {
        const loginTime = parseInt(loginTimeStr, 10);
        const SEVEN_DAYS_MS = 7 * 24 * 60 * 60 * 1000;
        if (!isNaN(loginTime) && Date.now() - loginTime > SEVEN_DAYS_MS) isExpired = true;
      }
      if (token && !isExpired) {
        return NextResponse.redirect(new URL('/admin', req.url));
      }
    }

    res = NextResponse.next();
  }

  if (
    pathname.startsWith('/admin') ||
    pathname.startsWith('/ops') ||
    pathname.startsWith('/trinetra') ||
    pathname.startsWith('/agencyportal') ||
    pathname.startsWith('/guardportal') ||
    pathname.startsWith('/login') ||
    isOpsSubdomain ||
    isTrinetraSubdomain ||
    isApSubdomain ||
    isGuardSubdomain
  ) {
    res.headers.set('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0');
    res.headers.set('Pragma', 'no-cache');
    res.headers.set('Expires', '0');
    res.headers.set('Surrogate-Control', 'no-store');
  }

  return res;
}

export const config = {
  matcher: [
    '/((?!_next/static|_next/image|favicon.ico|suraksha-mark.png|logo.png).*)',
  ],
};
